---
title: "data_exploration"
output: html_document
date: "2025-01-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(dplyr)
library(tidyr)
library(ggplot2)

wd_processed_data <- "C:/Users/inbar/OneDrive/desktop/r/chapter_2/MoBr/data/processed" 

# read: 
setwd(wd_processed_data)
combined_data <- read.csv("combined_long.csv")
combined_data <- combined_data %>% dplyr::select(-X) 
```



Data preparations:
```{r}
combined_data = combined_data %>% arrange(value)

fish_abundance <- combined_data %>% filter(taxon == "fish", diversity_measure == "abundance")
fish_richness <- combined_data %>% filter(taxon == "fish", diversity_measure == "richness")
fish_evenness <- combined_data %>% filter(taxon == "fish", diversity_measure == "sigma")

sponges_abundance <- combined_data %>% filter(taxon == "sponges", diversity_measure == "abundance")
sponges_richness <- combined_data %>% filter(taxon == "sponges", diversity_measure == "richness")
sponges_evenness <- combined_data %>% filter(taxon == "sponges", diversity_measure == "sigma")

stony_abundance <- combined_data %>% filter(taxon == "stony corals", diversity_measure == "abundance")
stony_richness <- combined_data %>% filter(taxon == "stony corals", diversity_measure == "richness")
stony_evenness <- combined_data %>% filter(taxon == "stony corals", diversity_measure == "sigma")

soft_abundance <- combined_data %>% filter(taxon == "soft corals", diversity_measure == "abundance")
soft_richness<- combined_data %>% filter(taxon == "soft corals", diversity_measure == "richness")
soft_evenness <- combined_data %>% filter(taxon == "soft corals", diversity_measure == "sigma")

# Subset data for abundance, richness, and evenness
abundance_data <- combined_data[combined_data$diversity_measure == "abundance", ]
richness_data <- combined_data[combined_data$diversity_measure == "richness", ]
evenness_data <- combined_data[combined_data$diversity_measure == "sigma", ]

# wide format:
wide_data <- combined_data %>% pivot_wider(names_from = diversity_measure, values_from = value)

# wide_taxon:
numeric_for_vis_fish <- wide_data %>% dplyr::filter(taxon == "fish") %>% dplyr::select(depth, abundance, richness, sigma) 
numeric_for_vis_sponges <- wide_data %>% dplyr::filter(taxon == "sponges") %>% dplyr::select(depth, abundance, richness, sigma) 
numeric_for_vis_stony <- wide_data %>% dplyr::filter(taxon == "stony corals") %>% dplyr::select(depth, abundance, richness, sigma) 
numeric_for_vis_soft <- wide_data %>% dplyr::filter(taxon == "soft corals") %>% dplyr::select(depth, abundance, richness, sigma) 

# functions script:
# shorter version by Dor et al 

taxas <- wide_data %>%
  pull(taxon) %>%
  unique() %>%
  as.list %>%
  purrr::set_names(.)

numeric_per_taxa <- purrr::map(taxas,
           function(taxa) {
             wide_data %>%
               dplyr::filter(taxon == taxa) %>%
               dplyr::select(depth, abundance, richness, sigma) 
           })
```



```{r}
# Dotcharts for each diversity measure - identify outliers:
dotchart(fish_abundance$value,bg='orchid', main = "Abundance For Fish",)
dotchart(fish_richness$value,bg='orchid', main = "Richness For Fish",)
dotchart(fish_evenness$value,bg='orchid', main = "Evenness For Fish",)

dotchart(sponges_abundance$value,bg='blue', main = "Abundance For sponges",)
dotchart(sponges_richness$value,bg='blue', main = "Richness For sponges",)
dotchart(sponges_evenness$value,bg='blue', main = "Evenness For sponges",)

dotchart(stony_abundance$value,bg='darkgreen', main = "Abundance For stony",)
dotchart(stony_richness$value,bg='darkgreen', main = "Richness For stony",)
dotchart(stony_evenness$value,bg='darkgreen', main = "Evenness For stony",)

dotchart(soft_abundance$value,bg='darkred', main = "Abundance For soft",)
dotchart(soft_richness$value,bg='darkred', main = "Richness For soft",)
dotchart(soft_evenness$value,bg='darkred', main = "Evenness For soft",)

# which of the data point is an outlier?
```



```{r}
# outliers by the IQR:

ggplot(fish_abundance, aes(x = depth, y = value)) +
  geom_point(size = 3, alpha = 0.7) +
  geom_hline(yintercept = quantile(fish_abundance$value, 0.75) + 1.5 * IQR(fish_abundance$value), 
             linetype = "dashed", color = "red") +  # Upper outlier threshold
  geom_hline(yintercept = quantile(fish_abundance$value, 0.25) - 1.5 * IQR(fish_abundance$value), 
             linetype = "dashed", color = "red") +  # Lower outlier threshold
  labs(
    title = "Fish -Dotplot with Potential Outliers Highlighted",
    x = "Taxonomic Group",
    y = "abundance"
  ) +
  theme_minimal()


ggplot(fish_richness, aes(x = depth, y = value)) +
  geom_point(size = 3, alpha = 0.7) +
  geom_hline(yintercept = quantile(fish_richness$value, 0.75) + 1.5 * IQR(fish_richness$value), 
             linetype = "dashed", color = "red") +  # Upper outlier threshold
  geom_hline(yintercept = quantile(fish_richness$value, 0.25) - 1.5 * IQR(fish_richness$value), 
             linetype = "dashed", color = "red") +  # Lower outlier threshold
  labs(
    title = "Fish -Dotplot with Potential Outliers Highlighted",
    x = "Taxonomic Group",
    y = "richness"
  ) +
  theme_minimal()


ggplot(fish_evenness, aes(x = depth, y = value)) +
  geom_point(size = 3, alpha = 0.7) +
  geom_hline(yintercept = quantile(fish_evenness$value, 0.75) + 1.5 * IQR(fish_evenness$value), 
             linetype = "dashed", color = "red") +  # Upper outlier threshold
  geom_hline(yintercept = quantile(fish_evenness$value, 0.25) - 1.5 * IQR(fish_evenness$value), 
             linetype = "dashed", color = "red") +  # Lower outlier threshold
  labs(
    title = "Fish - Dotplot with Potential Outliers Highlighted",
    x = "Taxonomic Group",
    y = "eveness Measure Value"
  ) +
  theme_minimal()


# outliers by the IQR:

ggplot(sponges_abundance, aes(x = depth, y = value)) +
  geom_point(size = 3, alpha = 0.7) +
  geom_hline(yintercept = quantile(sponges_abundance$value, 0.75) + 1.5 * IQR(sponges_abundance$value), 
             linetype = "dashed", color = "red") +  # Upper outlier threshold
  geom_hline(yintercept = quantile(sponges_abundance$value, 0.25) - 1.5 * IQR(sponges_abundance$value), 
             linetype = "dashed", color = "red") +  # Lower outlier threshold
  labs(
    title = "Sponges - Dotplot with Potential Outliers Highlighted",
    x = "Taxonomic Group",
    y = "abundance"
  ) +
  theme_minimal()


ggplot(sponges_richness, aes(x = depth, y = value)) +
  geom_point(size = 3, alpha = 0.7) +
  geom_hline(yintercept = quantile(sponges_richness$value, 0.75) + 1.5 * IQR(sponges_richness$value), 
             linetype = "dashed", color = "red") +  # Upper outlier threshold
  geom_hline(yintercept = quantile(sponges_richness$value, 0.25) - 1.5 * IQR(sponges_richness$value), 
             linetype = "dashed", color = "red") +  # Lower outlier threshold
  labs(
    title = "Sponges - Dotplot with Potential Outliers Highlighted",
    x = "Taxonomic Group",
    y = "richness"
  ) +
  theme_minimal()


ggplot(sponges_evenness, aes(x = depth, y = value)) +
  geom_point(size = 3, alpha = 0.7) +
  geom_hline(yintercept = quantile(sponges_evenness$value, 0.75, na.rm = TRUE) + 1.5 * IQR(sponges_evenness$value, na.rm = TRUE), 
             linetype = "dashed", color = "red") +  # Upper outlier threshold
  geom_hline(yintercept = quantile(sponges_evenness$value, 0.25,na.rm = TRUE) - 1.5 * IQR(sponges_evenness$value, na.rm = TRUE), 
             linetype = "dashed", color = "red") +  # Lower outlier threshold
  labs(
    title = "Sponges - Dotplot with Potential Outliers Highlighted",
    x = "Taxonomic Group",
    y = "evenness"
  ) +
  theme_minimal()


# stony - outliers by the IQR:

ggplot(stony_abundance, aes(x = depth, y = value)) +
  geom_point(size = 3, alpha = 0.7) +
  geom_hline(yintercept = quantile(stony_abundance$value, 0.75) + 1.5 * IQR(stony_abundance$value), 
             linetype = "dashed", color = "red") +  # Upper outlier threshold
  geom_hline(yintercept = quantile(stony_abundance$value, 0.25) - 1.5 * IQR(stony_abundance$value), 
             linetype = "dashed", color = "red") +  # Lower outlier threshold
  labs(
    title = "Stony -Dotplot with Potential Outliers Highlighted",
    x = "Taxonomic Group",
    y = "abundance"
  ) +
  theme_minimal()


ggplot(stony_richness, aes(x = depth, y = value)) +
  geom_point(size = 3, alpha = 0.7) +
  geom_hline(yintercept = quantile(stony_richness$value, 0.75) + 1.5 * IQR(stony_richness$value), 
             linetype = "dashed", color = "red") +  # Upper outlier threshold
  geom_hline(yintercept = quantile(stony_richness$value, 0.25) - 1.5 * IQR(stony_richness$value), 
             linetype = "dashed", color = "red") +  # Lower outlier threshold
  labs(
    title = "Stony -Dotplot with Potential Outliers Highlighted",
    x = "Taxonomic Group",
    y = "richness"
  ) +
  theme_minimal()


ggplot(stony_evenness, aes(x = depth, y = value)) +
  geom_point(size = 3, alpha = 0.7) +
  geom_hline(yintercept = quantile(stony_evenness$value, 0.75) + 1.5 * IQR(stony_evenness$value), 
             linetype = "dashed", color = "red") +  # Upper outlier threshold
  geom_hline(yintercept = quantile(stony_evenness$value, 0.25) - 1.5 * IQR(stony_evenness$value), 
             linetype = "dashed", color = "red") +  # Lower outlier threshold
  labs(
    title = "Stony - Dotplot with Potential Outliers Highlighted",
    x = "Taxonomic Group",
    y = "evenness"
  ) +
  theme_minimal()

# soft - outliers by the IQR:

ggplot(soft_abundance, aes(x = depth, y = value)) +
  geom_point(size = 3, alpha = 0.7) +
  geom_hline(yintercept = quantile(soft_abundance$value, 0.75) + 1.5 * IQR(soft_abundance$value), 
             linetype = "dashed", color = "red") +  # Upper outlier threshold
  geom_hline(yintercept = quantile(soft_abundance$value, 0.25) - 1.5 * IQR(soft_abundance$value), 
             linetype = "dashed", color = "red") +  # Lower outlier threshold
  labs(
    title = "Soft -Dotplot with Potential Outliers Highlighted",
    x = "Taxonomic Group",
    y = "abundance"
  ) +
  theme_minimal()


ggplot(soft_richness, aes(x = depth, y = value)) +
  geom_point(size = 3, alpha = 0.7) +
  geom_hline(yintercept = quantile(soft_richness$value, 0.75) + 1.5 * IQR(soft_richness$value), 
             linetype = "dashed", color = "red") +  # Upper outlier threshold
  geom_hline(yintercept = quantile(soft_richness$value, 0.25) - 1.5 * IQR(soft_richness$value), 
             linetype = "dashed", color = "red") +  # Lower outlier threshold
  labs(
    title = "Soft - Dotplot with Potential Outliers Highlighted",
    x = "Taxonomic Group",
    y = "richness"
  ) +
  theme_minimal()


ggplot(soft_evenness, aes(x = depth, y = value)) +
  geom_point(size = 3, alpha = 0.7) +
  geom_hline(yintercept = quantile(soft_evenness$value, 0.75) + 1.5 * IQR(soft_evenness$value), 
             linetype = "dashed", color = "red") +  # Upper outlier threshold
  geom_hline(yintercept = quantile(soft_evenness$value, 0.25) - 1.5 * IQR(soft_evenness$value), 
             linetype = "dashed", color = "red") +  # Lower outlier threshold
  labs(
    title = "Soft - Dotplot with Potential Outliers Highlighted",
    x = "Taxonomic Group",
    y = "evenness"
  ) +
  theme_minimal()

```



```{r}
       # box plot - diversity vs depth

boxplot(abundance_data$value ~ abundance_data$taxon) 
boxplot(richness_data$value ~ richness_data$taxon) 
boxplot(evenness_data$value ~ evenness_data$taxon) 
```


Histograms for all diversity measures
```{r}
#abundance:
ggplot(abundance_data, aes(x = value)) +
  geom_histogram(binwidth = 10, fill = "skyblue", color = "black", alpha = 0.7) +
  facet_wrap(~ taxon, scales = "free_y") +  # Separate by taxonomic group
  labs(title = "Histogram of Abundance by Taxonomic Group",
       x = "Abundance",
       y = "Frequency") +
  theme_minimal()

#richness:
ggplot(richness_data, aes(x = value)) +
  geom_histogram(binwidth = 1, fill = "darkgreen", color = "black", alpha = 0.7) +
  facet_wrap(~ taxon, scales = "free_y") +  # Separate by taxonomic group
  labs(title = "Histogram of Richness by Taxonomic Group",
       x = "Richness",
       y = "Frequency") +
  theme_minimal()

#evenness:
ggplot(evenness_data, aes(x = value)) +
  geom_histogram(binwidth = 0.5, fill = "darkred", color = "black", alpha = 0.7) +
  facet_wrap(~ taxon, scales = "free_y") +  # Separate by taxonomic group
  labs(title = "Histogram of Evenness by Taxonomic Group",
       x = "Evenness",
       y = "Frequency") +
  theme_minimal()
```

*****************************************************************
              
                    #### Collinearity  

*****************************************************************

```{r}
pairs(numeric_for_vis_fish, cex.labels= 1)
pairs(numeric_for_vis_sponges, cex.labels= 1)
pairs(numeric_for_vis_stony, cex.labels= 1)
pairs(numeric_for_vis_soft, cex.labels= 1)
```

violin plot:
```{r}
#abundance:
ggplot(abundance_data, aes(x = taxon, y = value, fill = taxon)) +
  geom_violin() +
  geom_jitter(width = 0.1)+
  labs(
    title = "Abundance violin by Taxonomic Group",
    y = "abundance",
    fill = "Taxon"
  ) +
  theme_minimal()

#richness:
ggplot(richness_data, aes(x = taxon, y = value, fill = taxon)) +
  geom_violin() +
  geom_jitter(width = 0.1)+
  labs(
    title = "Richness violin by Taxonomic Group",
    y = "richness",
    fill = "Taxon"
  ) +
  theme_minimal()

#evenness:
ggplot(evenness_data, aes(x = taxon, y = value, fill = taxon)) +
  geom_violin() +
  geom_jitter(width = 0.1)+
  labs(
    title = "Evenness violin by Taxonomic Group",
    y = "Evenness",
    fill = "Taxon"
  ) +
  theme_minimal()
```


boxplot:
```{r}
ggplot(combined_data, aes(x = taxon, y = value, fill = diversity_measure)) +
  geom_boxplot() +
  facet_wrap(~ diversity_measure, scales = "free_y") +
  labs(
    title = "Boxplots of Diversity Measures by Taxonomic Group",
    x = "Taxonomic Group",
    y = "Value",
    fill = "Diversity Measure"
  ) +
  theme_minimal()
```






